apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - homarr-secret.yaml
  - homarr-auth-secret.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - ingress.yaml
