apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - internal-ca.yaml
  - cert-mealie.yaml
  - cert-drawio.yaml
  - cert-homarr.yaml
  - cert-traefik.yaml
  - cert-grafana.yaml
  - cert-grafana-wc.yaml
  - cert-minio.yaml
  - cert-plane.yaml
  - cert-bar-assistant.yaml
  - cert-nextcloud.yaml
