apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - meilisearch-deployment.yaml
  - redis-deployment.yaml
  - server-deployment.yaml
  - salt-rim-deployment.yaml
  - ingress.yaml
